import {test,expect} from '@playwright/test';
const address='0x489594537CB76aC256079D710B6E18498E1a5402';
test('failed balances are unavailable, chain changes clear identity, and reconnect reads actual network',async({page})=>{
 await page.addInitScript(({address})=>{let chain='0x38';const listeners={};window.ethereum={on:(e,f)=>listeners[e]=f,request:async({method})=>{if(['eth_accounts','eth_requestAccounts'].includes(method))return[address];if(method==='eth_chainId')return chain;if(method==='eth_blockNumber')return '0x1';throw Error('RPC unavailable');}};window.changeNetwork=()=>{chain='0x13b2';listeners.chainChanged?.(chain);};},{address});
 await page.goto('/bridge.html');await expect(page.locator('#connect')).toBeEnabled();await page.locator('#asset-select').selectOption('cat');await expect(page.locator('#token-balance')).toHaveText('暂未取得');await expect(page.locator('#balance-note')).toContainText('不代表余额为零');await page.evaluate(()=>window.changeNetwork());await expect(page.locator('#account')).toHaveText('未连接');await expect(page.locator('#token-balance')).toHaveText('连接钱包后查询');await page.locator('#connect').click();await expect(page.locator('#network')).toHaveText('Arc Mainnet');await expect(page.locator('#prepare-approve')).toBeHidden();
});
test('unresponsive restore times out and late account result cannot restore stale identity',async({page})=>{
 await page.clock.install();await page.addInitScript(({address})=>{window.ethereum={on:()=>{},request:({method})=>{if(method==='eth_accounts')return new Promise(resolve=>window.resolveAccounts=()=>resolve([address]));if(method==='eth_chainId')return Promise.resolve('0x38');throw Error('Unexpected '+method);}};},{address});await page.goto('/bridge.html');await page.waitForFunction(()=>typeof window.resolveAccounts==='function');await page.clock.fastForward(11000);await expect(page.locator('#connect')).toBeEnabled();await expect(page.locator('#message')).toContainText('重新检查钱包授权');await page.evaluate(()=>window.resolveAccounts());await expect(page.locator('#account')).toHaveText('未连接');
});
test('TVPILOT balance uses this accounts recorded token',async({page})=>{
 await page.addInitScript(({address})=>{localStorage.setItem('tevumi-pilot-deployments-v1',JSON.stringify([{kind:'PilotToken',chainId:56,account:address,address:'0x1111111111111111111111111111111111111111',txHash:'0x'+'1'.repeat(64)}]));window.ethereum={on:()=>{},request:async({method})=>{if(method==='eth_accounts')return[address];if(method==='eth_chainId')return '0x38';if(method==='eth_getBalance')return '0x0';if(method==='eth_blockNumber')return '0x1';if(method==='eth_call')return '0x'+(10n**18n).toString(16).padStart(64,'0');throw Error('Unexpected '+method);}};},{address});await page.goto('/bridge.html');await expect(page.locator('#token-balance')).toHaveText('1.0 TVPILOT');
});
